# Usamos la imagen oficial de Node.js para compilar la aplicación Angular
FROM node:18.12.0 AS builder

# Instala Angular CLI de forma global
RUN npm install -g @angular/cli

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de configuración y el archivo package.json
COPY package*.json ./
COPY angular.json ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY tsconfig.spec.json ./
COPY src/ ./src/

# Instalar las dependencias
RUN npm install

# Compilar la aplicación Angular
RUN ng build --configuration production

# Usar la imagen oficial de Nginx como imagen base para servir la aplicación
FROM nginx:alpine

# Copiar los archivos de la compilación de Angular en el directorio de Nginx
COPY --from=builder /app/dist/devsu-finanzas-ang /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 4200

# Comando para iniciar el servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
